//! H.264 test vector tests using externally-produced bitstreams.
//!
//! These vectors are Annex B bitstreams generated by ffmpeg's libx264.
//! They validate that our decoder handles bitstreams from external encoders,
//! not just our own openh264 output.
//!
//! # Vectors
//!
//! | File | Profile | Frames | Resolution | Content |
//! |------|---------|--------|------------|---------|
//! | `idr_16x16_blue.h264` | Baseline | 1 IDR | 16×16 | Solid blue |
//! | `idr_32x32_red.h264` | Baseline | 1 IDR | 32×32 | Solid red |
//! | `seq_32x32_green_6f.h264` | Baseline | 6 (I+P) | 32×32 | Solid green |
//! | `seq_32x32_main_3f.h264` | Main | 3 (I+P) | 32×32 | Solid yellow |
//! | `seq_64x64_pattern_5f.h264` | Baseline | 5 (I+P) | 64×64 | Test pattern |

use std::time::Duration;

use crate::{
    codec::h264::annexb,
    config::{H264, VideoCodec, VideoConfig},
    format::{DecodeConfig, DecoderBackend, MediaPacket, PixelFormat},
    traits::VideoDecoder,
};

// Embed test vectors at compile time.
const IDR_16X16_BLUE: &[u8] = include_bytes!("vectors/idr_16x16_blue.h264");
const IDR_32X32_RED: &[u8] = include_bytes!("vectors/idr_32x32_red.h264");
const SEQ_32X32_GREEN_6F: &[u8] = include_bytes!("vectors/seq_32x32_green_6f.h264");
const SEQ_32X32_MAIN_3F: &[u8] = include_bytes!("vectors/seq_32x32_main_3f.h264");
const SEQ_64X64_PATTERN_5F: &[u8] = include_bytes!("vectors/seq_64x64_pattern_5f.h264");

/// Splits an Annex B bitstream into per-access-unit packets using NAL type boundaries.
///
/// Groups NALs into access units: each IDR (type 5) or non-IDR slice (type 1)
/// starts a new access unit. SPS/PPS/SEI/AUD NALs are prepended to the next slice.
fn split_access_units(data: &[u8]) -> Vec<MediaPacket> {
    let nals = annexb::parse_annex_b(data);
    let mut packets = Vec::new();
    let mut current_au = Vec::new();
    let mut is_keyframe = false;
    let mut ts = Duration::ZERO;
    let frame_dur = Duration::from_millis(33); // ~30fps

    for nal in &nals {
        if nal.is_empty() {
            continue;
        }
        let nal_type = nal[0] & 0x1F;

        // Slice NAL (IDR=5, non-IDR=1) marks the start of a new access unit
        // if we already have slice data accumulated.
        if (nal_type == 1 || nal_type == 5)
            && current_au.iter().any(|n: &Vec<u8>| {
                let t = n[0] & 0x1F;
                t == 1 || t == 5
            })
        {
            // Emit previous access unit.
            let payload = nals_to_annex_b(&current_au);
            packets.push(MediaPacket {
                timestamp: ts,
                payload: payload.into(),
                is_keyframe,
            });
            ts += frame_dur;
            current_au.clear();
            is_keyframe = false;
        }

        if nal_type == 5 {
            is_keyframe = true;
        }
        current_au.push(nal.to_vec());
    }

    // Emit last access unit.
    if !current_au.is_empty() {
        let payload = nals_to_annex_b(&current_au);
        packets.push(MediaPacket {
            timestamp: ts,
            payload: payload.into(),
            is_keyframe,
        });
    }

    packets
}

fn nals_to_annex_b(nals: &[Vec<u8>]) -> Vec<u8> {
    let mut out = Vec::new();
    for nal in nals {
        out.extend_from_slice(&[0, 0, 0, 1]);
        out.extend_from_slice(nal);
    }
    out
}

/// Creates a VideoConfig for H.264 Annex B decoding (inline SPS/PPS).
fn h264_config(width: u32, height: u32) -> VideoConfig {
    VideoConfig {
        codec: VideoCodec::H264(H264 {
            profile: 0x42,
            constraints: 0,
            level: 10,
            inline: true,
        }),
        description: None,
        coded_width: Some(width),
        coded_height: Some(height),
        display_ratio_width: None,
        display_ratio_height: None,
        bitrate: None,
        framerate: None,
        optimize_for_latency: None,
    }
}

/// Decodes all packets with the software H.264 decoder.
fn decode_all(
    config: &VideoConfig,
    packets: Vec<MediaPacket>,
) -> Vec<crate::format::DecodedVideoFrame> {
    let dc = DecodeConfig {
        backend: DecoderBackend::Software,
        pixel_format: PixelFormat::Rgba,
    };
    let mut dec = crate::codec::h264::decoder::H264VideoDecoder::new(config, &dc).unwrap();
    let mut frames = Vec::new();
    for pkt in packets {
        dec.push_packet(pkt).unwrap();
        if let Some(f) = dec.pop_frame().unwrap() {
            frames.push(f);
        }
    }
    frames
}

// ── Annex B parsing tests with real bitstreams ───────────────────────

#[test]
fn parse_real_bitstream_nal_types() {
    let nals = annexb::parse_annex_b(IDR_32X32_RED);
    assert!(
        nals.len() >= 3,
        "expected SPS+PPS+IDR, got {} NALs",
        nals.len()
    );

    let types: Vec<u8> = nals.iter().map(|n| n[0] & 0x1F).collect();
    // Should contain SPS (7), PPS (8), and IDR slice (5)
    assert!(types.contains(&7), "missing SPS (type 7), found: {types:?}");
    assert!(types.contains(&8), "missing PPS (type 8), found: {types:?}");
    assert!(types.contains(&5), "missing IDR (type 5), found: {types:?}");
}

#[test]
fn parse_real_bitstream_sps_pps_extraction() {
    let nals = annexb::parse_annex_b(IDR_32X32_RED);
    let (sps, pps) = annexb::extract_sps_pps(&nals).expect("should find SPS and PPS");
    // SPS should start with type 7
    assert_eq!(sps[0] & 0x1F, 7);
    // PPS should start with type 8
    assert_eq!(pps[0] & 0x1F, 8);
}

#[test]
fn avcc_roundtrip_with_real_bitstream() {
    let nals = annexb::parse_annex_b(IDR_32X32_RED);
    let (sps, pps) = annexb::extract_sps_pps(&nals).unwrap();
    let avcc = annexb::build_avcc(&sps, &pps);
    let annex_b = annexb::avcc_to_annex_b(&avcc).unwrap();
    let recovered_nals = annexb::parse_annex_b(&annex_b);
    assert_eq!(recovered_nals.len(), 2);
    assert_eq!(recovered_nals[0], &sps[..]);
    assert_eq!(recovered_nals[1], &pps[..]);
}

#[test]
fn annex_b_length_prefixed_roundtrip_real() {
    let nals = annexb::parse_annex_b(IDR_16X16_BLUE);
    // Convert full bitstream to length-prefixed and back.
    let lp = annexb::annex_b_to_length_prefixed(IDR_16X16_BLUE);
    let back = annexb::length_prefixed_to_annex_b(&lp);
    let recovered_nals = annexb::parse_annex_b(&back);
    assert_eq!(nals.len(), recovered_nals.len());
    for (orig, recov) in nals.iter().zip(recovered_nals.iter()) {
        assert_eq!(*orig, *recov);
    }
}

#[test]
fn multi_frame_bitstream_has_p_frames() {
    let nals = annexb::parse_annex_b(SEQ_32X32_GREEN_6F);
    let types: Vec<u8> = nals.iter().map(|n| n[0] & 0x1F).collect();
    // Should have at least one non-IDR slice (type 1 = P/B frame).
    assert!(
        types.contains(&1),
        "expected P-frame (type 1) in multi-frame sequence, found: {types:?}"
    );
}

#[test]
fn main_profile_bitstream_parses() {
    let nals = annexb::parse_annex_b(SEQ_32X32_MAIN_3F);
    assert!(nals.len() >= 3, "expected at least 3 NALs for Main profile");
    let types: Vec<u8> = nals.iter().map(|n| n[0] & 0x1F).collect();
    assert!(types.contains(&7), "missing SPS in Main profile bitstream");
    assert!(types.contains(&8), "missing PPS in Main profile bitstream");
}

// ── Decoder tests with externally-produced bitstreams ─────────────────

#[test]
fn decode_external_idr_16x16_blue() {
    let packets = split_access_units(IDR_16X16_BLUE);
    assert!(!packets.is_empty());
    assert!(packets[0].is_keyframe);

    let config = h264_config(16, 16);
    let frames = decode_all(&config, packets);
    assert!(!frames.is_empty(), "decoder produced no frames");

    let img = frames[0].img();
    assert_eq!(img.width(), 16);
    assert_eq!(img.height(), 16);
    let pixel = img.get_pixel(8, 8);
    // Blue: R low, G low, B high
    assert!(
        pixel[2] > 100,
        "B={} should be high for blue frame",
        pixel[2]
    );
}

#[test]
fn decode_external_idr_32x32_red() {
    let packets = split_access_units(IDR_32X32_RED);
    let config = h264_config(32, 32);
    let frames = decode_all(&config, packets);
    assert!(!frames.is_empty());

    let img = frames[0].img();
    assert_eq!(img.width(), 32);
    assert_eq!(img.height(), 32);
    let pixel = img.get_pixel(16, 16);
    // Red: R high, G low, B low
    assert!(
        pixel[0] > 100,
        "R={} should be high for red frame",
        pixel[0]
    );
}

#[test]
fn decode_external_sequence_green_6f() {
    let packets = split_access_units(SEQ_32X32_GREEN_6F);
    assert!(
        packets.len() >= 2,
        "expected multiple packets for 6-frame sequence"
    );

    let config = h264_config(32, 32);
    let frames = decode_all(&config, packets);
    assert!(
        frames.len() >= 2,
        "expected >= 2 decoded frames, got {}",
        frames.len()
    );

    // Check last frame (decoder fully warmed up).
    let last = frames.last().unwrap();
    let img = last.img();
    assert_eq!(img.width(), 32);
    assert_eq!(img.height(), 32);
    let pixel = img.get_pixel(16, 16);
    // Green: G high
    assert!(
        pixel[1] > 100,
        "G={} should be high for green frame",
        pixel[1]
    );
}

#[test]
fn decode_external_main_profile_3f() {
    // Main profile uses CABAC instead of CAVLC.
    let packets = split_access_units(SEQ_32X32_MAIN_3F);
    let config = h264_config(32, 32);
    let frames = decode_all(&config, packets);
    assert!(
        !frames.is_empty(),
        "decoder should handle Main profile (CABAC) bitstreams"
    );

    let img = frames.last().unwrap().img();
    assert_eq!(img.width(), 32);
    assert_eq!(img.height(), 32);
    // Yellow: R high, G high, B low
    let pixel = img.get_pixel(16, 16);
    assert!(
        pixel[0] > 100 && pixel[1] > 100,
        "R={} G={} should be high for yellow",
        pixel[0],
        pixel[1]
    );
}

#[test]
fn decode_external_pattern_64x64_5f() {
    let packets = split_access_units(SEQ_64X64_PATTERN_5F);
    let config = h264_config(64, 64);
    let frames = decode_all(&config, packets);
    assert!(
        frames.len() >= 2,
        "expected >= 2 decoded frames from pattern sequence, got {}",
        frames.len()
    );

    // Pattern frame should not be all black.
    let last = frames.last().unwrap();
    let img = last.img();
    assert_eq!(img.width(), 64);
    assert_eq!(img.height(), 64);
    let mut total_brightness: u64 = 0;
    for y in [16, 32, 48] {
        for x in [16, 32, 48] {
            let p = img.get_pixel(x, y);
            total_brightness += p[0] as u64 + p[1] as u64 + p[2] as u64;
        }
    }
    assert!(
        total_brightness > 0,
        "decoded pattern frame should not be all black"
    );
}

#[test]
fn decode_external_with_bgra_output() {
    let packets = split_access_units(IDR_32X32_RED);
    let config = h264_config(32, 32);
    let dc = DecodeConfig {
        backend: DecoderBackend::Software,
        pixel_format: PixelFormat::Bgra,
    };
    let mut dec = crate::codec::h264::decoder::H264VideoDecoder::new(&config, &dc).unwrap();
    let mut frames = Vec::new();
    for pkt in packets {
        dec.push_packet(pkt).unwrap();
        if let Some(f) = dec.pop_frame().unwrap() {
            frames.push(f);
        }
    }
    assert!(!frames.is_empty());

    if let crate::format::FrameBuffer::Cpu(ref cpu) = frames[0].buffer {
        assert_eq!(cpu.pixel_format, PixelFormat::Bgra);
        // In BGRA, red pixel has: B=low(0), G=low(1), R=high(2), A=255(3)
        let mid = ((16 * 32 + 16) * 4) as usize;
        assert!(
            cpu.image.as_raw()[mid + 2] > 100,
            "BGRA R channel should be high for red frame"
        );
    } else {
        panic!("expected CPU frame");
    }
}

#[test]
fn decode_external_with_viewport_scaling() {
    let packets = split_access_units(SEQ_64X64_PATTERN_5F);
    let config = h264_config(64, 64);
    let dc = DecodeConfig {
        backend: DecoderBackend::Software,
        pixel_format: PixelFormat::Rgba,
    };
    let mut dec = crate::codec::h264::decoder::H264VideoDecoder::new(&config, &dc).unwrap();
    dec.set_viewport(32, 32);

    let mut last_frame = None;
    for pkt in packets {
        dec.push_packet(pkt).unwrap();
        if let Some(f) = dec.pop_frame().unwrap() {
            last_frame = Some(f);
        }
    }

    let frame = last_frame.expect("should decode at least one frame");
    let (w, h) = frame.dimensions();
    assert!(w <= 32, "width {w} should be <= 32 after viewport scaling");
    assert!(h <= 32, "height {h} should be <= 32 after viewport scaling");
}

// ── DynamicVideoDecoder with external vectors ────────────────────────

#[test]
fn dynamic_decoder_routes_external_h264() {
    let packets = split_access_units(IDR_32X32_RED);
    let config = h264_config(32, 32);
    let dc = DecodeConfig {
        backend: DecoderBackend::Software,
        ..Default::default()
    };
    let mut dec = crate::codec::DynamicVideoDecoder::new(&config, &dc).unwrap();
    assert_eq!(dec.name(), "h264-openh264");

    let mut decoded_count = 0;
    for pkt in packets {
        dec.push_packet(pkt).unwrap();
        if dec.pop_frame().unwrap().is_some() {
            decoded_count += 1;
        }
    }
    assert!(
        decoded_count >= 1,
        "DynamicVideoDecoder should decode external vectors"
    );
}
