name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ci-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: 1
  RUSTFLAGS: -Dwarnings
  RUSTDOCFLAGS: -Dwarnings

jobs:
  check_fmt:
    timeout-minutes: 30
    name: Checking fmt
    runs-on: [self-hosted, linux, X64]
    env:
      RUSTC_WRAPPER: "sccache"
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - uses: mozilla-actions/sccache-action@v0.0.9
      - run: cargo fmt --all -- --check

  clippy_check:
    timeout-minutes: 30
    name: Clippy
    runs-on: [self-hosted, linux, X64]
    env:
      RUSTC_WRAPPER: "sccache"
    steps:
      - uses: actions/checkout@v4

      - name: Install build deps
        run: |
          sudo apt-get update && sudo apt-get install -y \
            libx264-dev libpipewire-0.3-dev pkg-config libasound2-dev libegl1-mesa-dev libgl1-mesa-dev libx11-dev \
            clang curl ca-certificates llvm libssl-dev yasm nasm libopus-dev libva-dev libva-drm2 libdrm-dev \
            libxext-dev libxfixes-dev libgbm-dev libxkbcommon-dev libxkbcommon-x11-dev libavutil-dev libavutil ffmpeg

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: mozilla-actions/sccache-action@v0.0.9

      - name: Clippy (all features)
        run: cargo clippy --workspace --all-features --all-targets

      - name: Clippy (default features)
        run: cargo clippy --workspace --all-targets

  tests:
    timeout-minutes: 30
    name: Tests (${{ matrix.name }})
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        name: [linux, macOS]
        include:
          - name: linux
            runner: [self-hosted, linux, X64]
          - name: macOS
            runner: [self-hosted, macOS, ARM64]
    env:
      RUSTC_WRAPPER: "sccache"
    steps:
      - uses: actions/checkout@v4

      - name: Install build deps (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update && sudo apt-get install -y \
            libx264-dev libpipewire-0.3-dev pkg-config libasound2-dev libegl1-mesa-dev libgl1-mesa-dev libx11-dev \
            clang curl ca-certificates llvm libssl-dev yasm nasm libopus-dev libva-dev libva-drm2 libdrm-dev \
            libxext-dev libxfixes-dev libgbm-dev libxkbcommon-dev libxkbcommon-x11-dev libavutil-dev libavutil ffmpeg

      - name: Install build deps (macOS)
        if: runner.os == 'macOS'
        run: brew install -q create-dmg pkg-config curl openssl@3 x264 yasm nasm opus ffmpeg automake autoconf libtool

      - uses: dtolnay/rust-toolchain@stable
      - uses: mozilla-actions/sccache-action@v0.0.9

      - name: Cargo check
        run: cargo check --workspace --examples --tests

      - name: Cargo test
        run: cargo test --workspace
